### ISSUE TITLE
Items Can Become Invisible in Player Inventory

### ISSUE THREAD

**Issue by Dborasik** [Dborasik/Dans-CombineControl#1]
When a player clicks on the "Throw Out" button in their inventory, the item on the list after the one which they threw out can sometimes disappear. If an admin checks that players inventory, the supposedly deleted item is still considered to be there but will remain invisible on the player's screen.

**Comment by AWildErin** [comment]
Small thing from me, I fixed this in my own fork, here's the specific commit where I fixed it: https://github.com/AWildErin/combinecontrol-ce/commit/7d796bd69b715861895eadecaa70528e8811f942

**Comment by Dborasik** [comment]
> Small thing from me, I fixed this in my own fork, here's the specific commit where I fixed it: [AWildErin/combinecontrol-ce@7d796bd](https://github.com/AWildErin/combinecontrol-ce/commit/7d796bd69b715861895eadecaa70528e8811f942)

Not going to lie, seems like a really simple fix. Thanks a lot!

**Comment by Dborasik** [comment]
Fixed in commit 6fa9198.
Thanks again @AWildErin!
